version: '3.8'
services:

  frontend:
    container_name: frontend
    image: node:20-alpine3.17
    working_dir: /app
    entrypoint: [ 'yarn', 'run', 'start' ]
    ports:
      - 3000:3000
    volumes:
      - .:/app
      